// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0f6MB-_emO9d-FRqWZs2AwB8mmJ3h8Q',
    appId: '1:434817206866:web:c730a87d04df66d937ed8b',
    messagingSenderId: '434817206866',
    projectId: 'docit-242a4',
    authDomain: 'docit-242a4.firebaseapp.com',
    databaseURL: 'https://docit-242a4-default-rtdb.firebaseio.com/',
    storageBucket: 'docit-242a4.appspot.com',
    measurementId: 'G-ZEF0NYXDQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbZho86pqgJM4S5eCbzad48OQmDb9bk4',
    appId: '1:434817206866:android:388f9e04c2c73ee037ed8b',
    messagingSenderId: '434817206866',
    projectId: 'docit-242a4',
    storageBucket: 'docit-242a4.appspot.com',
    databaseURL: 'https://docit-242a4-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoyreXJwvMdwUbbH5O3p0lvMtxQqFW6Uo',
    appId: '1:434817206866:ios:4efc1317f679bc1637ed8b',
    messagingSenderId: '434817206866',
    projectId: 'docit-242a4',
    storageBucket: 'docit-242a4.appspot.com',
    iosClientId: '434817206866-bpdn7ha46mprl4vrqj3odjletdkgkc7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.docit',
    databaseURL: 'https://docit-242a4-default-rtdb.firebaseio.com/',
  );
}
